async function getPayments() {
  const res = await fetch(process.env.API_URL + '/api/v1/portal/payments', { cache: 'no-store' });
  return res.json();
}
function Header(){return <header style={{height:82,background:'#382d28',color:'#fff',display:'flex',alignItems:'center',padding:'0 26px',gap:24}}><div style={{fontSize:24,fontWeight:800}}>NCBA CONNECT<span style={{color:'#39b5df'}}>PLUS</span></div><div style={{marginLeft:'auto',display:'flex',gap:28,fontSize:22}}><span>⌕</span><span>▢</span><span>✉</span><span>♢<sup style={{background:'#f44336',borderRadius:'50%',fontSize:12,padding:'2px 5px'}}>24</sup></span><span style={{fontSize:18}}>English⌄</span><span style={{width:42,height:42,borderRadius:'50%',background:'#eee',display:'inline-block'}}></span><span>⌄</span></div></header>}
function MiniSidebar(){const items=[['⌂','/portal'],['▣','/portal/account-services'],['▤','/portal/payments'],['♧','#'],['▧','/portal/reports']];return <aside style={{position:'fixed',top:82,bottom:0,left:0,width:64,background:'#382d28',color:'#fff',zIndex:2}}>{items.map((i,idx)=><a key={i[0]} href={i[1]} style={{height:58,display:'flex',alignItems:'center',justifyContent:'center',fontSize:25,color:'#fff',textDecoration:'none',background:idx===2?'#39b5df':'transparent'}}>{i[0]}</a>)}</aside>}
function QuickLinks(){const view=['Payments','Beneficiary','Billers','Standing Instructions','Lipa na MPesa'];const init=['Make a Payment','Add Beneficiary','Add Mobile Money','Add Lipa na MPesa','Add Float Purchase','Add Biller','Pesalink Link/Delink Request'];return <aside style={{background:'#dff4ff',border:'1px solid #c8dde8',padding:28,minHeight:610,fontSize:18,position:'relative'}}><div style={{position:'absolute',left:-25,top:40,width:48,height:48,borderRadius:'50%',background:'#fff',border:'1px solid #ccc',display:'flex',alignItems:'center',justifyContent:'center',fontSize:30}}>›</div><h2>Quick Links <span style={{float:'right'}}>?</span></h2><strong>⊙ View</strong><ul>{view.map(x=><li key={x} style={{margin:'14px 0'}}>{x}</li>)}</ul><div style={{textAlign:'right',fontWeight:700}}>Show more⌄</div><hr/><strong>✐ Initiate</strong><ul>{init.map(x=><li key={x} style={{margin:'14px 0'}}>{x}</li>)}</ul><div style={{textAlign:'right',fontWeight:700}}>Show Less⌃</div></aside>}

export default async function PaymentsPage(){
 const payments=await getPayments();
 return <main style={{fontFamily:'Arial, Helvetica, sans-serif',background:'#fafafa',minHeight:'100vh'}}><Header/><MiniSidebar/><section style={{marginLeft:64}}><div style={{background:'#fff',height:76,display:'flex',alignItems:'center',padding:'0 22px',borderBottom:'1px solid #ddd'}}><h1>Payments</h1></div><div style={{height:62,display:'flex',gap:44,alignItems:'center',paddingLeft:44,borderBottom:'1px solid #ddd',fontSize:18}}><strong>Single Payments (29)</strong><span>File Payments</span><span>Instruments</span><span>Bills</span></div><div style={{padding:28,display:'grid',gridTemplateColumns:'1fr 310px',gap:32}}><section style={{background:'#fff',border:'1px solid #ddd',padding:24,minHeight:610}}><div style={{display:'flex',gap:16,alignItems:'center',marginBottom:20}}><button style={{background:'#fff',border:'1px solid #ddd',padding:'10px 18px',fontSize:18}}>□ Group By</button><input placeholder="Search for Payments" style={{marginLeft:'auto',width:520,padding:'11px',fontSize:18,border:'1px solid #ddd'}}/><button style={{padding:10}}>⟳</button><button style={{padding:10}}>↓</button><button style={{padding:10}}>▣</button></div><table style={{width:'100%',borderCollapse:'collapse',fontSize:16}}><thead><tr style={{borderTop:'1px solid #ddd',borderBottom:'1px solid #ddd'}}>{['Credit To','Debit From','Payment Type','Reference Number','Core Reference Number','Amount','Action'].map(h=><th key={h} align="left" style={{padding:12}}>{h} ↕</th>)}</tr></thead><tbody>{payments.map((p:any,i:number)=><tr key={i} style={{borderBottom:'1px solid #eee',verticalAlign:'top'}}><td style={{padding:13}}><span style={{background:'#f00',color:'#f00',borderRadius:7}}>XXXX</span>{p.creditTo}<br/><span style={{background:p.status.includes('Rejected')?'#ffdbe3':'#d7f7f5',color:p.status.includes('Rejected')?'#e11d48':'#00a99d',borderRadius:16,padding:'6px 12px',fontSize:13}}>● {p.status}</span></td><td style={{padding:13}}><span style={{background:'#f00',color:'#f00',borderRadius:7}}>XXXX</span>{p.debitFrom}<br/><span style={{background:'#eee',borderRadius:16,padding:'5px 16px',fontSize:13}}>KES</span></td><td style={{padding:13}}>{p.paymentType}</td><td style={{padding:13}}>{p.referenceNumber}<span style={{background:'#f00',color:'#f00',borderRadius:7}}>XXX</span></td><td style={{padding:13}}>{p.coreReferenceNumber}<span style={{background:'#f00',color:'#f00',borderRadius:7}}>XXX</span></td><td style={{padding:13}}>{p.amount}<br/><br/>on {p.date}</td><td style={{padding:13,fontSize:26}}>⋮</td></tr>)}</tbody></table><div style={{fontSize:17,marginTop:18}}>Displaying 1 - 29 of 29 Payments <span style={{float:'right',color:'#777'}}>Items per page&nbsp; 100⌄ &nbsp;&nbsp; Page 1 of 1 ‹ ›</span></div></section><QuickLinks/></div></section></main>
}
// ✔ V15: Payments customer portal screen matching provided screenshot.
